#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short

#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

# setting temporary directory

export TMPDIR=~/qiime_tmp

#Beta Significance

time beta_significance.py -i ~/2018_02_smb/Core_Diversity_Analyses_Filtered_Samples/otu_table.biom -o Beta_Significance.txt -t ~/2018_02_smb/OTUs/97_otus.tree -s ~/2018_02_smb/Core_Diversity_Analyses/bdiv_even601/unweighted_unifrac_dm.txt

#deactivate

source deactivate
