#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short

#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

# setting temporary directory

export TMPDIR=~/qiime_tmp

time filter_samples_from_otu_table.py -i ~/2018_02_smb/OTUs/otu_table.biom -m ~/2018_02_smb/Mapping_File_COMPLETE.tsv -o OTUs_Filtered_By_Sample.biom --sample_id_fp ~/2018_02_smb/Mapping_File_COMPLETE.tsv

#deactivate

source deactivate
