#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short

#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

# setting temporary directory

export TMPDIR=~/qiime_tmp

#metadata correlation

time core_diversity_analyses.py -i ~/2018_02_smb/Core_Diversity_Analyses_Filtered_Samples/otu_table.biom -m ~/2018_02_smb/mapping_file_COMPLETE.tsv -o Observation_Metadata_Correlation -c SamplePh -o Observation_Metadata_Correlation_SamplePh

#deactivate

source deactivate
