#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short

#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

# setting temporary directory

export TMPDIR=~/qiime_tmp

#core diversity analysis 

time make_otu_heatmap.py -i ~/2018_02_smb/Core_Diversity_Analyses_Filtered_Samples/taxa_plots_SamplePh/SamplePh_otu_table_sorted_L2.biom -m Mapping_File_COMPLETE.tsv -o OTU_Heat_Map_Filtered_Samples.pdf -t ~/2018_02_smb/OTUs/97_otus.tree 

#deactivate

source deactivate
